"""add api_users.last_seen

Revision ID: 156b59250f33
Revises: 1f84f4203c8f
Create Date: 2025-12-04 10:35:31.642445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '156b59250f33'
down_revision: Union[str, Sequence[str], None] = '1f84f4203c8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_users', sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_users', 'last_seen')
    # ### end Alembic commands ###
