"""add group_vdbs_select_values

Revision ID: 445f136c55f3
Revises: e7970652942e
Create Date: 2026-02-07 15:43:58.175066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '445f136c55f3'
down_revision: Union[str, Sequence[str], None] = 'e7970652942e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_vdbs_select_values',
    sa.Column('gvsv_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gvdbs_id', sa.Integer(), nullable=False),
    sa.Column('gvsv_path', sa.VARCHAR(), nullable=False),
    sa.Column('gvsv_value', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('gvsv_id')
    )
    op.create_index(op.f('ix_group_vdbs_select_values_gvdbs_id'), 'group_vdbs_select_values', ['gvdbs_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_vdbs_select_values_gvdbs_id'), table_name='group_vdbs_select_values')
    op.drop_table('group_vdbs_select_values')
    # ### end Alembic commands ###
