"""add doc_tasks.output_text_2 column

Revision ID: 5b3d41a64493
Revises: faba5b767036
Create Date: 2025-11-17 05:40:33.804691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b3d41a64493'
down_revision: Union[str, Sequence[str], None] = 'faba5b767036'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doc_tasks', sa.Column('output_text_2', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doc_tasks', 'output_text_2')
    # ### end Alembic commands ###
