"""add group_vdbs.gvdbs_retr_filters

Revision ID: 644beac6388d
Revises: 893b0d874b05
Create Date: 2026-02-01 03:33:47.586762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '644beac6388d'
down_revision: Union[str, Sequence[str], None] = '893b0d874b05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_vdbs', sa.Column('gvdbs_retr_filters', sa.VARCHAR(), server_default=sa.text("'{}'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_vdbs', 'gvdbs_retr_filters')
    # ### end Alembic commands ###
