"""add enabled to group_llms group_vdbs

Revision ID: adf87cf4e03f
Revises: 156b59250f33
Create Date: 2025-12-04 11:34:36.035236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adf87cf4e03f'
down_revision: Union[str, Sequence[str], None] = '156b59250f33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_llms', sa.Column('enabled', sa.Boolean(), server_default=sa.text("'TRUE'"), nullable=False))
    op.create_index(op.f('ix_group_llms_enabled'), 'group_llms', ['enabled'], unique=False)
    op.add_column('group_vdbs', sa.Column('enabled', sa.Boolean(), server_default=sa.text("'TRUE'"), nullable=False))
    op.create_index(op.f('ix_group_vdbs_enabled'), 'group_vdbs', ['enabled'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_vdbs_enabled'), table_name='group_vdbs')
    op.drop_column('group_vdbs', 'enabled')
    op.drop_index(op.f('ix_group_llms_enabled'), table_name='group_llms')
    op.drop_column('group_llms', 'enabled')
    # ### end Alembic commands ###
