"""add doc_tasks.question_number column

Revision ID: b2a6141d5fde
Revises: 5b3d41a64493
Create Date: 2025-11-17 06:03:30.905299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2a6141d5fde'
down_revision: Union[str, Sequence[str], None] = '5b3d41a64493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doc_tasks', sa.Column('question_number', sa.Integer(), nullable=False, server_default=sa.text("1")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doc_tasks', 'question_number')
    # ### end Alembic commands ###
