"""add group_vdbs_tasks

Revision ID: e7970652942e
Revises: 644beac6388d
Create Date: 2026-02-07 15:11:58.048592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7970652942e'
down_revision: Union[str, Sequence[str], None] = '644beac6388d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_vdbs_tasks',
    sa.Column('gvt_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gvdbs_id', sa.Integer(), nullable=False),
    sa.Column('gvt_type', sa.Integer(), nullable=False),
    sa.Column('gvt_status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('gvt_id'),
    sa.UniqueConstraint('gvdbs_id', 'gvt_type', name='uq_gvdbs_id_gvt_type')
    )
    op.create_index(op.f('ix_group_vdbs_tasks_gvt_status'), 'group_vdbs_tasks', ['gvt_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_vdbs_tasks_gvt_status'), table_name='group_vdbs_tasks')
    op.drop_table('group_vdbs_tasks')
    # ### end Alembic commands ###
