"""add doc_tasks.gvdbs_cfg_json column

Revision ID: faba5b767036
Revises: 
Create Date: 2025-11-08 23:46:30.212533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faba5b767036'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doc_tasks', sa.Column('gvdbs_cfg_json', sa.Text(), server_default=sa.text("'{}'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doc_tasks', 'gvdbs_cfg_json')
    # ### end Alembic commands ###
